name: Mirror upstream main
on:
  repository_dispatch:
    types: [ mirror-upstream ]
jobs:
  mirror:
    runs-on: ubuntu-latest
    concurrency:
      group: fork-mirror
      cancel-in-progress: true
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add upstream and fetch
        run: |
          git remote add upstream Kozvelemeny-org/hu-polling-2026.git
          git fetch upstream
      - name: Mirror upstream/main to origin/main
        run: |
          git config user.name "mirror-bot"
          git config user.email "actions@users.noreply.github.com"
          git checkout -B main
          git reset --hard upstream/main
          git push origin main --force
